### ISSUE TITLE
Random Menger Sponge

### ISSUE THREAD

**Issue by GQMP** [vincentvigon/MATHIS2#15]
Le tableau des volumes à supprimer est mal rempli ; il doit toujours être une liste de triplets. (cf Menger Sponge juste au dessus.) (Ce qui corrige l'erreur avec subdivider = 2.)

@vincentvigon

**Comment by vincentvigon** [comment]
Super, désolé pour cette erreur bête. Je ne m'en était pas douté parce que cela marchait avec des tableaux de taille 4 (mais c'est logique).
